from src.utils.google_drive_download_datasets import download_augmented_spoken_mnist_dataset
from src.utils.google_drive_download_datasets import download_real_world_spoken_mnist_dataset
from src.utils.google_drive_download_datasets import download_real_world_complex_dataset
from src.utils.google_drive_download_datasets import download_real_world_spoken_test_dataset

from src.data.map_and_pickle_dataset import map_augmented_spoken_mnist_dataset
from src.data.map_and_pickle_dataset import map_real_world_spoken_mnist_dataset
from src.data.map_and_pickle_dataset import map_real_world_complex_dataset
from src.data.map_and_pickle_dataset import map_real_world_spoken_test_dataset

from src.models.model_train import compile_model, train_model_plot_and_save

from src.models.model_test import test_all_trained_models


download_augmented_spoken_mnist_dataset()
download_real_world_spoken_mnist_dataset()
download_real_world_complex_dataset()
download_real_world_spoken_test_dataset()

map_augmented_spoken_mnist_dataset()
map_real_world_spoken_mnist_dataset()
map_real_world_complex_dataset()
map_real_world_spoken_test_dataset()

baseline_model = compile_model(model_choice="baseline_model")
model_paper_code_1 = compile_model(model_choice="model_paper_code_1")
# model_paper_code_2 = compile_model(model_choice="model_paper_code_2")
model_paper_code_3 = compile_model(model_choice="model_paper_code_3")
model_paper_code_4 = compile_model(model_choice="model_paper_code_4")
model_paper_code_5 = compile_model(model_choice="model_paper_code_5")
model_paper_code_6 = compile_model(model_choice="model_paper_code_6")
model_paper_code_7 = compile_model(model_choice="model_paper_code_7")
model_paper_code_8 = compile_model(model_choice="model_paper_code_8")
model_paper_code_9 = compile_model(model_choice="model_paper_code_9")
model_paper_code_10 = compile_model(model_choice="model_paper_code_10")
model_paper_code_11 = compile_model(model_choice="model_paper_code_11")


train_model_plot_and_save(baseline_model)
train_model_plot_and_save(model_paper_code_1)
# train_model_plot_and_save(model_paper_code_2)
train_model_plot_and_save(model_paper_code_3)
train_model_plot_and_save(model_paper_code_4)
train_model_plot_and_save(model_paper_code_5)
train_model_plot_and_save(model_paper_code_6)
train_model_plot_and_save(model_paper_code_7)
train_model_plot_and_save(model_paper_code_8)
train_model_plot_and_save(model_paper_code_9)
train_model_plot_and_save(model_paper_code_10)
train_model_plot_and_save(model_paper_code_11)


test_all_trained_models()

